gsquire/sendgrid-rs

src/mail/mod.rs
src/sg_client/mod.rs

first test added

---

examples/main.rs

Easier style change for making more complex strings.

Example Update

---

Cargo.toml

upgrade to hyper 0.8

---

src/mail/mod.rs
src/sg_client/mod.rs

Use strings instead of slices.

Use String in Mail struct

---

README.md

A little tidying up, added information about other API key insertion options and the OpenSSL headers dependency.

README documentation expansion and clarifications.

---

Cargo.toml
README.md
examples/main.rs
src/lib.rs
src/sg_client/mod.rs

Fixes #9 and enforces proper encoding of the post body.

Use the url crate

---

examples/v3.rs
src/v3.rs

Fixes #25 
Implemented the `add_headers` function in v3 and updated the example with the custom headers for documentation purposes.
r? @gsquire

Create add_headers function in v3

---

Cargo.toml
src/errors.rs
src/sg_client.rs
src/v3.rs

Upgraded reqwest to 0.9
I actually really preferred the api in 0.8, but this seems to be the direction it's going.

Upgrade reqwest to 0.9

---

examples/main.rs
src/v3.rs

This adds support to provide the template id when using the v3 API.

Add support for template use

---

Cargo.toml
src/v3.rs

Add Clone + Debug to V3 Sender

---

Cargo.toml
examples/v3_async.rs
src/lib.rs
src/v3.rs

Hello,
I implemented Async call for v3 API.
I took inspiration from @peitalin pull request ( #47 ).
Regards,
Alexandre

Async feature for V3 API

---

Cargo.toml
examples/v3_async.rs
src/lib.rs
src/mail.rs
src/sg_client.rs
src/v3.rs

This patch creates a new release after merging in the asynchronous PR.
Items fixed:
- Polished the documentation
- Migrated to the 2018 edition of Rust
- Ran `rustfmt` and `clippy` over the code base
- Bump minor version

New Release Preparation

---

Cargo.toml
examples/v3_async.rs
src/errors.rs
src/lib.rs
src/v3.rs

This patch bumps the version and tidies up some stale imports and styling.

More 2018 Version Cleanup

---

Cargo.toml
README.md

This patch bumps the version and adds a note about the various feature flags supported within the crate.

New Release

---

Cargo.toml
src/errors.rs
src/sg_client.rs
src/v3.rs

add status code checks

---

Cargo.toml
src/v3.rs

@gsquire Excuse me for bother, just tested the async client and I missed an await for the future.

minor fix for async api

---

Cargo.toml
examples/v3.rs
examples/v3_async.rs
src/v3.rs

Resolves #44 
**What it does:**
- Enforce correctness by constructors
- Reduces clones by allowing passing directly strings
- Leverage `Option::get_or_insert_with`

New builder patterns

---

Cargo.toml

Bump `reqwest` and `tokio` versions

---

examples/v3.rs

Small change to clean up this example a little.

Make v3 example simpler & cleaner.

---

src/error.rs
src/v3.rs

allowing json objects for dynamic_template_data

---

src/v3.rs

Closes https://github.com/gsquire/sendgrid-rs/issues/87

Add reply_to to Message

---

src/client.rs
src/v3.rs

Fix #93 
\+ `cargo clippy --fix`

Add all remaining sets for Personalization

---

src/v3.rs

This is a small PR to expose additional SendGrid API options. I added a few tests that validate the additions are serialized correctly. The added settings add in tracking settings.

Add tracking settings

---

.github/workflows/ci.yml
src/client.rs
src/v3.rs

action-rs seems unmaintained and the dtolnay/rust-toolchain seems to be
the community's pick as a replacement. Also I have added clippy checks
and formatting checks.

Migrate away from action-rs

---

CHANGELOG.md

Add a Change Log

---

CHANGELOG.md
Cargo.toml
src/lib.rs

Update Feature Flags

---

CHANGELOG.md
Cargo.toml
src/v3.rs

I updated the change log and some documentation.

New Minor Version

---

CHANGELOG.md
Cargo.toml
src/v3/message.rs
src/v3/mod.rs

This incorporates #118 for a new release.

Version 0.23.0

---

src/v3/mod.rs

Separated async and blocking implementations to make the code cleaner.
Also made headers default for an inner client, instead of requesting them on every request.

Use default headers

---

CHANGELOG.md
Cargo.toml
README.md
src/client.rs
src/error.rs
src/v3/clients.rs
src/v3/mod.rs

This patch updates our clients to make them configure the necessary headers as default.

Client Update
