- src/v3.rs
StatusCode is used as part of a return type. It's common to re-export the type in this case.
Hyper has also been updated to 0.11... but that change is a lot more than I'm wanting to handle just yet. :D.
> Re-export the StatusCode as it's used in a return type

- src/v3.rs
There's a bcc field on the Personalization struct already, but no methods to access it. So this pr adds a method to add bccs to the personalization.
> add an add_bcc() function to allow bcc use

- Cargo.toml
- src/sg_client.rs
- src/v3.rs
This PR adjusts the function to check which fields to serialize as well as introduces the `reqwest::Response` type. This allows users to read the body or check headers as needed.
Fixes #23
> New return type for V3 mail send

- README.md
I am looking at integrating this and briefly was worried that I was going to have compatibility issues, but it turns out you already migrated!
> Update README to refer to reqwest and not hyper

- examples/main.rs
- src/lib.rs
- src/mail.rs
- src/sg_client.rs
- src/v3.rs
Heyo,
Feel free to push back on any/everything in here! I made a bunch of breaking changes, but I think with decent justification.
The switch from String's to &str is fairly important to me. I have an application which can't move ownership of it's metadata around, and copies get expensive pretty quickly.
The builder stuff isn't particularly important at all, but it does let you avoid having to make your Mail objects `mut` which is nice, and this is also a super common pattern in rust. The more common pattern is to have a MailBuilder which doesn't let you have a concrete Mail until you ::build(), I can implement that if you have the appetite but I wanted to get your thoughts on this.
We could also save a ton of copypasting by using a macro to generate these methods (ala …
> refactor mail

- Cargo.toml
- src/errors.rs
- src/lib.rs
- src/mail.rs
Let me know what you think. This obviously breaks some interfaces, I think the only real question is whether you want to return `failure::Errors`. Currently there's basically a roundtrip, since all the errors we wrap implement Fail.
cc #29
> Migrate from error chain to failure

- .travis.yml
- Cargo.toml
- examples/v3.rs
- src/v3.rs
This is a start of the migration to the builder pattern for the V3 module. The V2 module should be considered deprecated since V3 has been out for years now and is the preferred way to send messages using SendGrid's API. Unless there is a strong objection, I will mark it as deprecated.
Closes #30 
Closes #37 
Closes #38 
CC @Ten0 @otavio for review. The example has been updated to showcase the new API for now.
> V3 Builder

- Cargo.toml
To enhance cross-platform build - better to use [ring](https://github.com/briansmith/ring) over OpenSSL.
> Add feature rustls-tls to reqwest

- src/errors.rs
- src/sg_client.rs
- src/v3.rs
I tried using this with the new change and it turns out life is really hard when you can't know WHY the status code is not a success, so here is a follow-up PR.
> add response text for easier debug

- src/sg_client.rs
The [`ClientBuilder::use_rustls_tls`](https://docs.rs/reqwest/0.10.7/reqwest/struct.ClientBuilder.html#method.use_rustls_tls) method takes ownership of the builder, so we need to re-assign it. The current 0.12.0 version doesn't compile with a use-after-move error when the `rustls` feature is enabled.
> fix builder being moved with rustls feature enabled

- src/v3.rs
This is a small PR to expose additional SendGrid API options. I added a few tests that validate the additions are serialized correctly.
Please let me know if there are any additional changes needed.
Cheers,
Alex
> Add ip_pool_name and categories to Message

- src/v3.rs
We needed the ability to set the custom_args field in Personalization and the crate currently lacks the ability to do so. This PR adds a function to set the custom_args.
> Add a function to allow attaching custom_args to a Personalization

- src/v3.rs
I made a slight mistake in the previous PR where the tests did pass, but when used as a crate the fields in the tracking settings were private. I publicly exposed these fields & added documentation for them.
> Publicly expose fields in tracking settings

- src/error.rs
- src/v3.rs
Adds support for the ASM object which allows you to specify how to handle unsubscribes.
https://docs.sendgrid.com/api-reference/mail-send/mail-send
> Adds support for ASM

- src/client.rs
This allows easier testing for consumers of this library. The endpoint
can be set to be a local server to verify the email is sent correctly.
> Allow setting the the host endpoint

- src/v3.rs
I forgot v3 version of this when implementing it. See https://github.com/gsquire/sendgrid-rs/pull/99
> Add set host to V3 version of API

- .github/workflows/ci.yml
I should have updated this when I made the asynchronous runtime the default.
> Update CI Configuration

- examples/main.rs
- examples/v3.rs
- examples/v3_async.rs
- examples/v3_disable_tracking.rs
- src/lib.rs
- src/v3.rs
It would be useful to make it possible to use custom client. (to customize networking options)
> Allow using custom client

- .gitignore
- src/v3.rs
Adds Personalization::new_many to accept Vec<Email> for initializing a personalization to multiple email addresses without the requirement of a seed email address. 
Addresses #79 - it appears that #80 solves the same issue by deriving Default but was not merged in.
> Implement Personalization::new_many

- CHANGELOG.md
- Cargo.toml
- src/v3.rs
We implement the default trait on `Personalization` to simplify the API along with `new_many`.
> New Release

- src/v3/message.rs
- src/v3/mod.rs
Adds support for the `mail_settings` field of the [mail-send](https://www.twilio.com/docs/sendgrid/api-reference/mail-send/mail-send#request-body) API. This field includes the `sandbox_mode` setting, which allows sending the API to Sendgrid without actually sending the email to the recipient(s), which is useful for testing.
Closes https://github.com/gsquire/sendgrid-rs/issues/103
> feat: Add support for `mail_settings` message field

- Cargo.toml
- src/v3/mod.rs
This patch adds an example of using a custom client to help clear up any confusion.
Closes #123
> Add Documentation Example
